### ISSUE TITLE
Cant set MW3 installation folder because exe is named differently

### ISSUE THREAD

**Issue by SadSlothXL** [XLabsProject/iw4x-map-porting-utility#5]
Not able to set MW3 installation folder because exe has been renamed, you can get around this but renaming the exe back to the old name (open-iw5). Please update MPU to recognise the new exe name, thank you!

![image](https://github.com/iw4x/iw4x-map-porting-utility/assets/105758694/cac87f88-c3cc-4f9b-9cd4-56b9ca751478)
![image](https://github.com/iw4x/iw4x-map-porting-utility/assets/105758694/458fc382-8778-44b0-bd69-12b3dc587b6c)

**Comment by louvenarde** [comment]
i'm not sure what you expect me to do here.  i can't scan every EXE in the folder hoping one of them could be MW3
MPU expects iw5xport to be present in the folder that you select.  As of today the iw5xport release is consistently named `open-iw5.exe` as it is a fork of the open-iw5 project (and is pretty much the same, + extra code), so this is the expected name

what solution do you suggest?
i have a feeling what you call the "new exe name" is just a name you arbitrarily chose yourself, because i don't remember releasing a new version of iw5x-port that was named "iw5-mod.exe" (?).  but maybe I missed a memo or two :P

**Comment by SadSlothXL** [comment]
bump*

**Comment by louvenarde** [comment]
you never answered :)

**Comment by SadSlothXL** [comment]
When running the alterware-launcher in your mw3 install it will download an exe called iw5-mod, when trying to set your mw3 install with MPU you will get an error saying "Invalid path" because its looking for "open-iw5" which is the old alterware iw5 exe. This can be fixed by renaming open-iw5.exe in paths.cs and IW5xportHelper.cs to iw5-mod.exe

![image](https://github.com/user-attachments/assets/bbeacb41-271a-423e-b275-fef7c2c89481)

**Comment by louvenarde** [comment]
the IW5-mod that the alterware launcher downloads is NOT the IW5xport exporting tool.
https://github.com/iw4x/iw5x-port/releases/tag/v1.0.5 
IW5xport is always named open-iw5.exe
If you try to run iw5-mod.exe with MPU you will get.. nothing!

**Comment by SadSlothXL** [comment]
OHHH okay, thank you for explaining!
